"""add member sale lead fields

Revision ID: 071557b429a9
Revises: 
Create Date: 2026-07-02 14:20:14.279419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '071557b429a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sales_rep_id', sa.Integer(), nullable=True),
    sa.Column('referral_slug', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('clover_order_id', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('clover_checkout_id', sa.String(), nullable=True),
    sa.Column('clover_payment_id', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.Column('conversion_source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['membership_products.id'], ),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['sales_reps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.add_column('members', sa.Column('member_number', sa.String(), nullable=True))
    op.add_column('members', sa.Column('barcode', sa.String(), nullable=True))
    op.add_column('members', sa.Column('membership_start', sa.DateTime(), nullable=True))
    op.add_column('members', sa.Column('membership_end', sa.DateTime(), nullable=True))
    op.add_column('members', sa.Column('membership_status', sa.String(), nullable=True))
    op.add_column('members', sa.Column('auto_renew', sa.Boolean(), nullable=True))
    op.add_column('members', sa.Column('assigned_coach', sa.String(), nullable=True))
    op.add_column('members', sa.Column('waiver_signed', sa.Boolean(), nullable=True))
    op.add_column('sales', sa.Column('clover_checkout_id', sa.String(), nullable=True))
    op.add_column('sales', sa.Column('transaction_status', sa.String(), nullable=True))
    op.add_column('sales', sa.Column('refunded', sa.Boolean(), nullable=True))
    op.add_column('sales', sa.Column('refund_amount', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('payment_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'payment_method')
    op.drop_column('sales', 'refund_amount')
    op.drop_column('sales', 'refunded')
    op.drop_column('sales', 'transaction_status')
    op.drop_column('sales', 'clover_checkout_id')
    op.drop_column('members', 'waiver_signed')
    op.drop_column('members', 'assigned_coach')
    op.drop_column('members', 'auto_renew')
    op.drop_column('members', 'membership_status')
    op.drop_column('members', 'membership_end')
    op.drop_column('members', 'membership_start')
    op.drop_column('members', 'barcode')
    op.drop_column('members', 'member_number')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
